use_frameworks!

target 'AlamofireReactiveExtensions_Example' do
  pod 'AlamofireReactiveExtensions', :path => '../'

  target 'AlamofireReactiveExtensions_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
