use_frameworks!

target 'AlamofireReactiveExtensions_Example' do
  pod 'AlamofireReactiveExtensions', :path => '../'

  target 'AlamofireReactiveExtensions_Tests' do
    inherit! :search_paths

	pod 'Quick', '~> 1.2.0'
	pod 'Nimble', '~> 7.0.0'
  end
end
